[build]
  publish = "."             # O la carpeta donde está tu index.html y tus archivos estáticos (e.g., "public", "dist")
  functions = "netlify/functions" # Donde están tus funciones Netlify

[[redirects]]
  from = "/api/*"         # Ruta que tu frontend llamará (e.g., /api/gemini-proxy)
  to = "/.netlify/functions/:splat" # Ruta interna de Netlify Functions
  status = 200            # Asegura que sea un éxito HTTP
  force = true            # Fuerza la redirección para que se aplique siempre